# Generated by Django 3.2.5 on 2022-06-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Scheduled', max_length=256)),
                ('player1score', models.IntegerField(default=0)),
                ('player2score', models.IntegerField(default=0)),
                ('player3score', models.IntegerField(default=0)),
                ('winner', models.CharField(default='No Result Yet', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=256, unique=True)),
                ('match_points', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('byes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(to='petanqueapp.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='In Progress', max_length=256)),
                ('matches', models.ManyToManyField(to='petanqueapp.Match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petanqueapp.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='petanqueapp.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='petanqueapp.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='petanqueapp.player'),
        ),
    ]
