# Generated by Django 3.2.5 on 2022-07-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petanqueapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='round',
            name='matches',
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='round', to='petanqueapp.round'),
            preserve_default=False,
        ),
    ]
